run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    # CR: this appears to be not compliant with golangci-lint JSON Schema?
    - format: colored-line-number

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gocritic
    - unparam
    - thelper
    - nolintlint
    - gofmt
    - goimports
    - misspell
    - revive

# CR: this appears to be not compliant with golangci-lint JSON Schema?
linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: indent-error-flow
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
  wsl:
    allow-cuddle-declarations: false
    allow-assign-and-call: true

issues:
  # CR: this appears to be not compliant with golangci-lint JSON Schema?
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

# CR: can we somehow add # $schema: <url> and validate such files during `task lint`?
# to avoid mistakes
